/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PokemonImport } from './routes/pokemon'
import { Route as LandingImport } from './routes/landing'
import { Route as AdminImport } from './routes/admin'
import { Route as AuthImport } from './routes/_auth'
import { Route as MessagesRouteImport } from './routes/messages.route'
import { Route as DashboardRouteImport } from './routes/dashboard/route'
import { Route as IndexImport } from './routes/index'
import { Route as PokemonIndexImport } from './routes/pokemon.index'
import { Route as MessagesIndexImport } from './routes/messages.index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as CountIndexImport } from './routes/count.index'
import { Route as PokemonResultsImport } from './routes/pokemon.results'
import { Route as MessagesMessageIdImport } from './routes/messages.$messageId'
import { Route as CountTanstackImport } from './routes/count.tanstack'
import { Route as CountElysiaImport } from './routes/count.elysia'
import { Route as AdminDashboardImport } from './routes/admin/dashboard'
import { Route as AuthSignupImport } from './routes/_auth/signup'
import { Route as AuthSigninImport } from './routes/_auth/signin'
import { Route as AuthRegisterImport } from './routes/_auth/register'
import { Route as AuthLoginImport } from './routes/_auth/login'

// Create/Update Routes

const PokemonRoute = PokemonImport.update({
  id: '/pokemon',
  path: '/pokemon',
  getParentRoute: () => rootRoute,
} as any)

const LandingRoute = LandingImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const MessagesRouteRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PokemonIndexRoute = PokemonIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PokemonRoute,
} as any)

const MessagesIndexRoute = MessagesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MessagesRouteRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const CountIndexRoute = CountIndexImport.update({
  id: '/count/',
  path: '/count/',
  getParentRoute: () => rootRoute,
} as any)

const PokemonResultsRoute = PokemonResultsImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => PokemonRoute,
} as any)

const MessagesMessageIdRoute = MessagesMessageIdImport.update({
  id: '/$messageId',
  path: '/$messageId',
  getParentRoute: () => MessagesRouteRoute,
} as any)

const CountTanstackRoute = CountTanstackImport.update({
  id: '/count/tanstack',
  path: '/count/tanstack',
  getParentRoute: () => rootRoute,
} as any)

const CountElysiaRoute = CountElysiaImport.update({
  id: '/count/elysia',
  path: '/count/elysia',
  getParentRoute: () => rootRoute,
} as any)

const AdminDashboardRoute = AdminDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSigninRoute = AuthSigninImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingImport
      parentRoute: typeof rootRoute
    }
    '/pokemon': {
      id: '/pokemon'
      path: '/pokemon'
      fullPath: '/pokemon'
      preLoaderRoute: typeof PokemonImport
      parentRoute: typeof rootRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof AuthImport
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninImport
      parentRoute: typeof AuthImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof AuthImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardImport
      parentRoute: typeof AdminImport
    }
    '/count/elysia': {
      id: '/count/elysia'
      path: '/count/elysia'
      fullPath: '/count/elysia'
      preLoaderRoute: typeof CountElysiaImport
      parentRoute: typeof rootRoute
    }
    '/count/tanstack': {
      id: '/count/tanstack'
      path: '/count/tanstack'
      fullPath: '/count/tanstack'
      preLoaderRoute: typeof CountTanstackImport
      parentRoute: typeof rootRoute
    }
    '/messages/$messageId': {
      id: '/messages/$messageId'
      path: '/$messageId'
      fullPath: '/messages/$messageId'
      preLoaderRoute: typeof MessagesMessageIdImport
      parentRoute: typeof MessagesRouteImport
    }
    '/pokemon/results': {
      id: '/pokemon/results'
      path: '/results'
      fullPath: '/pokemon/results'
      preLoaderRoute: typeof PokemonResultsImport
      parentRoute: typeof PokemonImport
    }
    '/count/': {
      id: '/count/'
      path: '/count'
      fullPath: '/count'
      preLoaderRoute: typeof CountIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexImport
      parentRoute: typeof MessagesRouteImport
    }
    '/pokemon/': {
      id: '/pokemon/'
      path: '/'
      fullPath: '/pokemon/'
      preLoaderRoute: typeof PokemonIndexImport
      parentRoute: typeof PokemonImport
    }
  }
}

// Create and export the route tree

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface MessagesRouteRouteChildren {
  MessagesMessageIdRoute: typeof MessagesMessageIdRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
}

const MessagesRouteRouteChildren: MessagesRouteRouteChildren = {
  MessagesMessageIdRoute: MessagesMessageIdRoute,
  MessagesIndexRoute: MessagesIndexRoute,
}

const MessagesRouteRouteWithChildren = MessagesRouteRoute._addFileChildren(
  MessagesRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PokemonRouteChildren {
  PokemonResultsRoute: typeof PokemonResultsRoute
  PokemonIndexRoute: typeof PokemonIndexRoute
}

const PokemonRouteChildren: PokemonRouteChildren = {
  PokemonResultsRoute: PokemonResultsRoute,
  PokemonIndexRoute: PokemonIndexRoute,
}

const PokemonRouteWithChildren =
  PokemonRoute._addFileChildren(PokemonRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/messages': typeof MessagesRouteRouteWithChildren
  '': typeof AuthRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/landing': typeof LandingRoute
  '/pokemon': typeof PokemonRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/count/elysia': typeof CountElysiaRoute
  '/count/tanstack': typeof CountTanstackRoute
  '/messages/$messageId': typeof MessagesMessageIdRoute
  '/pokemon/results': typeof PokemonResultsRoute
  '/count': typeof CountIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/pokemon/': typeof PokemonIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/landing': typeof LandingRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/count/elysia': typeof CountElysiaRoute
  '/count/tanstack': typeof CountTanstackRoute
  '/messages/$messageId': typeof MessagesMessageIdRoute
  '/pokemon/results': typeof PokemonResultsRoute
  '/count': typeof CountIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/pokemon': typeof PokemonIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/messages': typeof MessagesRouteRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/landing': typeof LandingRoute
  '/pokemon': typeof PokemonRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/count/elysia': typeof CountElysiaRoute
  '/count/tanstack': typeof CountTanstackRoute
  '/messages/$messageId': typeof MessagesMessageIdRoute
  '/pokemon/results': typeof PokemonResultsRoute
  '/count/': typeof CountIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/pokemon/': typeof PokemonIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/messages'
    | ''
    | '/admin'
    | '/landing'
    | '/pokemon'
    | '/login'
    | '/register'
    | '/signin'
    | '/signup'
    | '/admin/dashboard'
    | '/count/elysia'
    | '/count/tanstack'
    | '/messages/$messageId'
    | '/pokemon/results'
    | '/count'
    | '/dashboard/'
    | '/messages/'
    | '/pokemon/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/admin'
    | '/landing'
    | '/login'
    | '/register'
    | '/signin'
    | '/signup'
    | '/admin/dashboard'
    | '/count/elysia'
    | '/count/tanstack'
    | '/messages/$messageId'
    | '/pokemon/results'
    | '/count'
    | '/dashboard'
    | '/messages'
    | '/pokemon'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/messages'
    | '/_auth'
    | '/admin'
    | '/landing'
    | '/pokemon'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/admin/dashboard'
    | '/count/elysia'
    | '/count/tanstack'
    | '/messages/$messageId'
    | '/pokemon/results'
    | '/count/'
    | '/dashboard/'
    | '/messages/'
    | '/pokemon/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  MessagesRouteRoute: typeof MessagesRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LandingRoute: typeof LandingRoute
  PokemonRoute: typeof PokemonRouteWithChildren
  CountElysiaRoute: typeof CountElysiaRoute
  CountTanstackRoute: typeof CountTanstackRoute
  CountIndexRoute: typeof CountIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  MessagesRouteRoute: MessagesRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LandingRoute: LandingRoute,
  PokemonRoute: PokemonRouteWithChildren,
  CountElysiaRoute: CountElysiaRoute,
  CountTanstackRoute: CountTanstackRoute,
  CountIndexRoute: CountIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/messages",
        "/_auth",
        "/admin",
        "/landing",
        "/pokemon",
        "/count/elysia",
        "/count/tanstack",
        "/count/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard/route.tsx",
      "children": [
        "/dashboard/"
      ]
    },
    "/messages": {
      "filePath": "messages.route.tsx",
      "children": [
        "/messages/$messageId",
        "/messages/"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/login",
        "/_auth/register",
        "/_auth/signin",
        "/_auth/signup"
      ]
    },
    "/admin": {
      "filePath": "admin.tsx",
      "children": [
        "/admin/dashboard"
      ]
    },
    "/landing": {
      "filePath": "landing.tsx"
    },
    "/pokemon": {
      "filePath": "pokemon.tsx",
      "children": [
        "/pokemon/results",
        "/pokemon/"
      ]
    },
    "/_auth/login": {
      "filePath": "_auth/login.tsx",
      "parent": "/_auth"
    },
    "/_auth/register": {
      "filePath": "_auth/register.tsx",
      "parent": "/_auth"
    },
    "/_auth/signin": {
      "filePath": "_auth/signin.tsx",
      "parent": "/_auth"
    },
    "/_auth/signup": {
      "filePath": "_auth/signup.tsx",
      "parent": "/_auth"
    },
    "/admin/dashboard": {
      "filePath": "admin/dashboard.tsx",
      "parent": "/admin"
    },
    "/count/elysia": {
      "filePath": "count.elysia.tsx"
    },
    "/count/tanstack": {
      "filePath": "count.tanstack.tsx"
    },
    "/messages/$messageId": {
      "filePath": "messages.$messageId.tsx",
      "parent": "/messages"
    },
    "/pokemon/results": {
      "filePath": "pokemon.results.tsx",
      "parent": "/pokemon"
    },
    "/count/": {
      "filePath": "count.index.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    },
    "/messages/": {
      "filePath": "messages.index.tsx",
      "parent": "/messages"
    },
    "/pokemon/": {
      "filePath": "pokemon.index.tsx",
      "parent": "/pokemon"
    }
  }
}
ROUTE_MANIFEST_END */
